# print(123456)
print(1234)
print('Luiz', 'Octávio', 'Outra coisa',sep='-', end='')
print('José', 'Dembo', sep='-', end='')
# print('Jose', 'Pedro', 'Daniel', 'Dembo', sep='/', end='')
# print('executar')
